name:                scheme-repl
version:             0.1.0.0
github:              "rvolosatovs/scheme-repl"
license:             BSD3
author:              "Roman Volosatovs, Eduardo del Palacio Lirola"
maintainer:          "rvolosatovs@riseup.net"
copyright:           "2018 Roman Volosatovs, Eduardo del Palacio Lirola"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/rvolosatovs/scheme-repl#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1.13.0
- mtl >= 2.2.2

library:
  source-dirs: src

executables:
  scheme-repl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scheme-repl

tests:
  scheme-repl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scheme-repl
